### ISSUE TITLE
after long time open it tries to load, but no sucess. menu still works

### ISSUE THREAD

**Issue by ThomasRausU** [openhab/openhab-android#1767]
### Actual behaviour
I have an wall tablet, which has only openhab app running. After some time the sitemap is not displayed. Just showing the loading circle. App itself is not hanging, menu changes are possible. Only changing the server url back and forth it's working correct for a while.

### Expected behaviour
app should not lose it's connection over time. Reconnection shouldn't be any problem

 
### Steps to reproduce
1. wait

### Can you reproduce the issue in demo mode?

-> don't know yet, trying. But since its connection related I bet it's not reproduceably in demo mode

#### Client
* Android version: 8.1.0
* Device model: TERRA_PAD_1005P0KO
* App version : 2.11.5-beta 8.1.2020  (tried it which default non beta version, same problem)
* Build flavor : Full
* Device language: de

#### Server
* Server version: 2.5.1~20200108044053-1 (and non beta same problem)
* Reverse Proxy: 
* Authentication method : None

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: 
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
no entry

**Comment by ThomasRausU** [comment]
-----------------------
Device information
Fingerprint: TERRA/TERRA_PAD_1005POKO/TERRA_PAD_1005POKO:8.1.0/O11019/vID100103:user/release-keys
Model: TERRA_PAD_1005POKO
Manufacturer: WORTMANN AG
Brand: TERRA
Device: TERRA_PAD_1005POKO
Product: TERRA_PAD_1005POKO
OS: 8.1.0
-----------------------

--------- beginning of events
01-12 19:17:14.010 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 19:19:19.159 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 19:19:19.198 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
01-12 19:40:25.639 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 19:43:07.865 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 19:43:07.909 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
01-12 19:46:34.966 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 19:50:15.376 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 19:50:15.416 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
01-12 20:12:56.074 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 20:14:57.917 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 20:14:57.957 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
01-12 22:23:53.724 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 22:28:47.914 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 22:28:47.951 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
01-12 22:28:56.145 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 22:29:10.631 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,handlePauseActivity]
01-12 22:29:11.019 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,LAUNCH_ACTIVITY]
01-12 22:29:11.794 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,handleStopActivity]
01-12 22:29:21.954 29935 29935 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handlePauseActivity]
01-12 22:29:21.989 29935 29935 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
01-12 22:29:22.330 29935 29935 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,destroy]

**Comment by ThomasRausU** [comment]
I was wrong - demomode is also affected!
[demomodeprotocol.txt](https://github.com/openhab/openhab-android/files/4052203/demomodeprotocol.txt)

**Comment by ThomasRausU** [comment]
and switching demo off and on fix the problem.

**Comment by mueller-ma** [comment]
> and switching demo off and on fix the problem.

So you don't experience this issue anymore?

**Comment by ThomasRausU** [comment]
no no no  - issue is just fixed for a few hours. Either you switch demo mode off and on or switching url back and forth.

**Comment by mueller-ma** [comment]
Can you turn on debug logging in the settings and send me a log after this issue has been occurred?

**Comment by ThomasRausU** [comment]
[ChangePortToWrongAndBackAndErrorIsGone.txt](https://github.com/openhab/openhab-android/files/4079197/ChangePortToWrongAndBackAndErrorIsGone.txt)
[SwitchingOnDebugLogWhileErrorIsPresent.txt](https://github.com/openhab/openhab-android/files/4079198/SwitchingOnDebugLogWhileErrorIsPresent.txt)

**Comment by ThomasRausU** [comment]
[LogWhileErrorAfterAbout8h.txt](https://github.com/openhab/openhab-android/files/4080148/LogWhileErrorAfterAbout8h.txt)
This morning the error was there - here is the log. If there is anything I can try, please tell me. I love openhab and this app and like to get it running stable!

**Comment by mueller-ma** [comment]
I can think of two improvements that should fix this issue:
1. Limit the time where the app shows only the loading indicator. If the timeout is reached display an error page.
2. On the error pages automatically retry every minute or so.

**Comment by ThomasRausU** [comment]
Tested in 2.11.14-beta and bug still is there. As said even in demo mode it occurs. I don't have a clue how you implement demo mode, but might this info helps. thx

**Comment by mueller-ma** [comment]
Demo mode is just a regular connection to the demo server (http://demo.openhab.org:8080/basicui/app).

**Comment by ThomasRausU** [comment]
fixed by version: https://github.com/openhab/openhab-android/releases/tag/2.11.15-beta 
thanks!

**Comment by ThomasRausU** [comment]
sorry, it's not fixed - took just longer time.
