### ISSUE TITLE
GUI missing text while using Arabic language in device

### ISSUE THREAD

**Issue by ahmed89albttashi** [openhab/openhab-android#827]
### Actual behaviour
Some text not appear

### Expected behaviour
to display same navigation as using English language

 
### Steps to reproduce
1. Change Mobile language to Arabic 
2. open app and click to  menu 

### Can you reproduce the issue in demo mode?
yes

#### Client
* Android version: 8
* Device model: Huawei nova 2 plus
* Stock or customized ROM: official rom 
* App version 2.0.0
* Device language: Arabic 

in normal mode
![screenshot_20180407-231513](https://user-images.githubusercontent.com/6708191/38459490-4e5346e2-3abb-11e8-870d-5fabbd75fbe5.png)

demo mode 
![screenshot_20180407-231622](https://user-images.githubusercontent.com/6708191/38459486-46d9420e-3abb-11e8-83f5-189de5662906.png)

**Comment by mueller-ma** [comment]
Hey @ahmed89albttashi,
thanks for filling out this bug report. The bug is already fixed, but the fix is not released yet. #533

**Comment by ahmed89albttashi** [comment]
Thanks you @mueller-ma  , Any deadline to see this release ?
+ 
whom are managing Arabic translations , I have translate more than half of Andorid project but still not approved 

Regards

**Comment by mueller-ma** [comment]
> whom are managing Arabic translations

Nobody, but you could do it. @ThomDietrich can give you proofreader permissions.

**Comment by mueller-ma** [comment]
@ahmed89albttashi Can you check if it's fixed in the latest version?

**Comment by ahmed89albttashi** [comment]
first congrats for new release.

yes it's fixed
